package com.shifa.oms.order;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.constraints.IntRange;

import java.util.HashSet;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property-based test for order-code uniqueness (design §Correctness
 * Properties (10), §6.1).
 *
 * Feature: role-based-order-workflow, Property 10: Order codes are unique.
 *
 * **Validates: Requirements 5.5**
 *
 * <p>For any batch of codes generated by {@link OrderCodeGenerator} against the
 * running set of already-issued codes (the same {@code existsByOrderCode}-style
 * uniqueness predicate the repository provides), every produced code is pairwise
 * distinct and carries the expected {@code SHR-} prefix.
 *
 * <p>Pure, in-memory logic: a real {@link OrderCodeGenerator} over an in-memory
 * {@link Set} predicate; no Spring, no persistence, no mocks. Each
 * {@code @Property} runs the jqwik default of 1000 tries (≥ 100).
 */
class OrderCodeUniquenessPropertyTest {

    // Feature: role-based-order-workflow, Property 10: Order codes are unique
    // **Validates: Requirements 5.5**
    @Property
    void generatedOrderCodesArePairwiseDistinct(@ForAll @IntRange(min = 1, max = 80) int count) {
        OrderCodeGenerator generator = new OrderCodeGenerator();
        Set<String> issued = new HashSet<>();

        for (int i = 0; i < count; i++) {
            String code = generator.generate(issued::contains);
            assertThat(code).startsWith("SHR-");
            // add() returns false if the code was already present → collision.
            boolean fresh = issued.add(code);
            assertThat(fresh)
                    .as("order code %s must be unique", code)
                    .isTrue();
        }

        assertThat(issued).hasSize(count);
    }
}
